{% set name = "dask-sql" %}
{% set version = "0.1.0rc4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dask_sql-{{ version }}.tar.gz
  sha256: 92c4f1d8aaf098af8b1d331addc6f2c5797b5d3a1fc992f5027f5e78c27c265d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - maven >=3.6.0
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - dask >=2.19.0
    - jpype1 >=1.0.2
    - python >=3.6
    - openjdk >=8

test:
  imports:
    - dask_sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/nils-braun/dask-sql/
  summary: SQL Query Layer for dask
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - nils-braun
